// Names of the icons the site can render. `Icon` must implement every name
// (checked with `satisfies`), so types never depend on components.
export type IconName =
  | 'arrowRight'
  | 'arrowUp'
  | 'bell'
  | 'calculator'
  | 'calendar'
  | 'camera'
  | 'check'
  | 'checkCircle'
  | 'chevronDown'
  | 'droplet'
  | 'feeding'
  | 'flask'
  | 'home'
  | 'plus'
  | 'menu'
  | 'close'
  | 'moon'
  | 'search'
  | 'sparkle'
  | 'star'
  | 'store'
  | 'sun'
  | 'tank'
  | 'thermometer'
  | 'user'
  | 'fish'
  | 'leaf'
  | 'fishBody'
  | 'shell'
  | 'alert'
  | 'list'
  | 'grid'
  | 'chevronLeft'
  | 'chevronRight'
  | 'dots'
