// Regenerates src/components/ui/iconData.ts from Phosphor Icons (MIT, @phosphor-icons/core).
// Run `node scripts/build-icons.mjs` after changing the map below; the output is committed,
// so the build never depends on this package at runtime.
import { readFileSync, writeFileSync } from 'node:fs'

const ASSETS = 'node_modules/@phosphor-icons/core/assets'

// site icon name -> [phosphor name, weight]. Objects use duotone; UI glyphs (arrows, carets, tick, plus...) use bold so they stay crisp at 14-20px.
const MAP = {
  arrowRight: ['arrow-right', 'bold'],
  arrowUp: ['arrow-up', 'bold'],
  bell: ['bell', 'duotone'],
  calculator: ['calculator', 'duotone'],
  calendar: ['calendar-blank', 'duotone'],
  camera: ['camera', 'duotone'],
  check: ['check', 'bold'],
  checkCircle: ['check-circle', 'duotone'],
  chevronDown: ['caret-down', 'bold'],
  droplet: ['drop', 'duotone'],
  feeding: ['bowl-food', 'duotone'],
  flask: ['flask', 'duotone'],
  home: ['house', 'duotone'],
  plus: ['plus', 'bold'],
  minus: ['minus', 'bold'],
  menu: ['list', 'bold'],
  close: ['x', 'bold'],
  moon: ['moon', 'duotone'],
  search: ['magnifying-glass', 'duotone'],
  sparkle: ['sparkle', 'duotone'],
  star: ['star', 'duotone'],
  store: ['storefront', 'duotone'],
  sun: ['sun', 'duotone'],
  tank: ['square-half-bottom', 'duotone'],
  thermometer: ['thermometer', 'duotone'],
  user: ['user', 'duotone'],
  fish: ['fish-simple', 'duotone'],
  leaf: ['plant', 'duotone'],
  shell: ['spiral', 'duotone'],
  alert: ['warning', 'duotone'],
  list: ['rows', 'bold'],
  grid: ['squares-four', 'bold'],
  chevronLeft: ['caret-left', 'bold'],
  chevronRight: ['caret-right', 'bold'],
  dots: ['dots-three-vertical', 'bold'],
}

const file = (name, weight) => `${ASSETS}/${weight}/${name}${weight === 'regular' ? '' : `-${weight}`}.svg`
const shapes = (svg) => [...svg.matchAll(/<path d="([^"]+)"(?: opacity="([\d.]+)")?\/>/g)].map((m) => (m[2] ? { d: m[1], opacity: Number(m[2]) } : { d: m[1] }))

const entries = Object.entries(MAP).map(([key, [name, weight]]) => {
  const parts = shapes(readFileSync(file(name, weight), 'utf8'))
  if (!parts.length) throw new Error(`no paths for ${name} (${weight})`)
  return `  ${key}: ${JSON.stringify(parts)},`
})

writeFileSync(
  'src/components/ui/iconData.ts',
  `// Generated by scripts/build-icons.mjs from Phosphor Icons (MIT, https://phosphoricons.com). Do not edit by hand.
export interface IconShape {
  d: string
  opacity?: number
}

export const iconData = {
${entries.join('\n')}
} as const satisfies Record<string, readonly IconShape[]>
`,
)
console.log(`wrote ${entries.length} icons`)
